### ISSUE TITLE
testBasicServer ERROR

### ISSUE THREAD

**Issue by PeterYFPeng** [dana-i2cat/netconf-server#14]
Client info below:
[net.i2cat.netconf.SessionContext] : Current path: C:\peter\MyWorkspace\indi\netconf-server
[net.i2cat.netconf.transport.TransportFactory] : Initializing transport factory
[net.i2cat.netconf.transport.TransportFactory] : Transport net.i2cat.netconf.transport.SSHTransport registered under scheme 'ssh'
[net.i2cat.netconf.transport.TransportFactory] : Transport net.i2cat.netconf.transport.MockTransport registered under scheme 'mock'
[net.i2cat.netconf.messageQueue.MessageQueue] : New listener
[net.i2cat.netconf.transport.SSHTransport] : user: ubuntu
[net.i2cat.netconf.transport.SSHTransport] : pass: yes
[net.i2cat.netconf.transport.SSHTransport] : hostname: localhost:2222
[net.i2cat.netconf.transport.SSHTransport] : subsystem: netconf
[net.i2cat.netconf.transport.SSHTransport] : Connecting to localhost
net.i2cat.netconf.errors.TransportException: IOException: There was a problem while connecting to localhost:2222
	at net.i2cat.netconf.transport.SSHTransport.connect(SSHTransport.java:148)
	at net.i2cat.netconf.NetconfSession.connect(NetconfSession.java:116)
	at net.i2cat.netconf.server.client.ClientApp.main(ClientApp.java:23)
Caused by: java.io.IOException: There was a problem while connecting to localhost:2222
	at ch.ethz.ssh2.Connection.connect(Connection.java:699)
	at ch.ethz.ssh2.Connection.connect(Connection.java:490)
	at net.i2cat.netconf.transport.SSHTransport.connect(SSHTransport.java:126)
	... 2 more
Caused by: java.io.IOException: Key exchange was not finished, connection is closed.
	at ch.ethz.ssh2.transport.KexManager.getOrWaitForConnectionInfo(KexManager.java:91)
	at ch.ethz.ssh2.transport.TransportManager.getConnectionInfo(TransportManager.java:229)
	at ch.ethz.ssh2.Connection.connect(Connection.java:655)
	... 4 more
Caused by: java.io.IOException: Cannot read full block, EOF reached.
	at ch.ethz.ssh2.crypto.cipher.CipherInputStream.getBlock(CipherInputStream.java:81)
	at ch.ethz.ssh2.crypto.cipher.CipherInputStream.read(CipherInputStream.java:108)
	at ch.ethz.ssh2.transport.TransportConnection.receiveMessage(TransportConnection.java:231)
	at ch.ethz.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:669)
	at ch.ethz.ssh2.transport.TransportManager$1.run(TransportManager.java:468)
	at java.lang.Thread.run(Thread.java:748)
[net.i2cat.netconf.transport.SSHTransport] : Connection with localhost lost:Cannot read full block, EOF reached.
[net.i2cat.netconf.NetconfSession] : Transport closed event

server error below:

[org.apache.sshd.common.io.nio2.Nio2Session] : Creating Nio2Session on /127.0.0.1:2222 from /127.0.0.1:50486
[org.apache.sshd.server.session.ServerSession] : Session created from /127.0.0.1:50486
[org.apache.sshd.common.io.nio2.Nio2Session] : Writing 25 bytes
[org.apache.sshd.server.keyprovider.SimpleGeneratorHostKeyProvider] : Generating host key...
[org.apache.sshd.server.keyprovider.SimpleGeneratorHostKeyProvider] : Unable to write key : java.io.FileNotFoundException: 
[org.apache.sshd.common.io.nio2.Nio2Session] : Writing 360 bytes
[org.apache.sshd.common.io.nio2.Nio2Session] : Read 27 bytes
[org.apache.sshd.server.session.ServerSession] : Client version string: SSH-2.0-Ganymed Build_210
[org.apache.sshd.common.io.nio2.Nio2Session] : Read 488 bytes
[org.apache.sshd.server.session.ServerSession] : Received packet SSH_MSG_KEXINIT
[org.apache.sshd.server.session.ServerSession] : Received SSH_MSG_KEXINIT
[org.apache.sshd.common.io.nio2.Nio2Session] : Read 144 bytes
[org.apache.sshd.server.session.ServerSession] : Received packet SSH_MSG_KEXDH_INIT
[org.apache.sshd.server.kex.DHG1] : Received SSH_MSG_KEXDH_INIT
[org.apache.sshd.common.io.nio2.Nio2Session] : Caught exception, now calling handler
[org.apache.sshd.server.session.ServerSession] : Exception caught
java.security.InvalidKeyException: The security strength of SHA-1 digest algorithm is not sufficient for this key size
	at sun.security.provider.DSA.checkKey(DSA.java:111)
	at sun.security.provider.DSA.engineInitSign(DSA.java:143)
	at java.security.Signature$Delegate.engineInitSign(Signature.java:1177)
	at java.security.Signature.initSign(Signature.java:530)
	at org.apache.sshd.common.signature.AbstractSignature.init(AbstractSignature.java:47)
	at org.apache.sshd.server.kex.AbstractDHGServer.next(AbstractDHGServer.java:93)
	at org.apache.sshd.server.session.ServerSession.handleMessage(ServerSession.java:177)
	at org.apache.sshd.common.session.AbstractSession.decode(AbstractSession.java:587)
	at org.apache.sshd.common.session.AbstractSession.messageReceived(AbstractSession.java:253)
	at org.apache.sshd.common.AbstractSessionIoHandler.messageReceived(AbstractSessionIoHandler.java:54)
	at org.apache.sshd.common.io.nio2.Nio2Session$2.completed(Nio2Session.java:231)
	at org.apache.sshd.common.io.nio2.Nio2Session$2.completed(Nio2Session.java:217)
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
	at sun.nio.ch.Invoker$2.run(Invoker.java:218)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[org.apache.sshd.server.session.ServerSession] : Closing session
[org.apache.sshd.server.session.ServerSession] : Closing IoSession
[org.apache.sshd.common.io.nio2.Nio2Session] : Closing Nio2Session
[org.apache.sshd.common.io.nio2.Nio2Session] : Closing socket
[org.apache.sshd.server.session.ServerSession] : IoSession closed
[org.apache.sshd.server.session.ServerSession] : Session null@/127.0.0.1:50486 closed

**Comment by PeterYFPeng** [comment]
I used RSA to work well.
AbstractGeneratorHostKeyProvider hostKeyProvider = new SimpleGeneratorHostKeyProvider("");
hostKeyProvider.setAlgorithm("RSA");
sshd.setKeyPairProvider(hostKeyProvider);
